databases:
  - name: postgres
    databaseName: e_commerce_shop
    user: robi
    ipAllowList: []

services:
  - type: web
    name: e-commerce-shop
    runtime: ruby
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/rails db:migrate"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
