default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: aaronmaliqi
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: e_commerce_shop_development

test:
  <<: *default
  database: e_commerce_shop_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: e_commerce_shop_development
  username: aaronmaliqi
  password: <%= ENV["E_COMMERCE_SHOP_DATABASE_PASSWORD"] %>
